# (yesterday, today, secondary)
CONDITION_RESPONSES = [
  ('clear', 'clear', "and it's another beautiful clear day!"),
  ('clear', 'clouds', "but it's cloudy."),
  ('clear', 'wet', "and it's raining. Fantastic."),
  ('clear', 'storm', "and there's a storm coming. Exciting!"),
  ('clear', 'freezing', "and there's ice everywhere."),
  ('clear', 'snow', "but look! There's snow!"),
  ('clouds', 'clear', "and the clouds have gone away!"),
  ('clouds', 'clouds', "but it's still cloudy."),
  ('clouds', 'wet', "and it's raining. Fantastic."),
  ('clouds', 'storm', "and there's a storm coming. Exciting!"),
  ('clouds', 'freezing', "and there's ice everywhere."),
  ('clouds', 'snow', "but look! There's snow!"),
  ('wet', 'clear', "but it's not raining anymore!"),
  ('wet', 'clouds', "but at least it's not raining!"),
  ('wet', 'wet', "and it's still raining."),
  ('wet', 'storm', "and there's a storm coming. Exciting!"),
  ('wet', 'freezing', "and there's ice everywhere."),
  ('wet', 'snow', "but look! There's snow!"),
  ('snow', 'clear', "and the sky has cleared."),
  ('snow', 'clouds', "but it's cloudy and the snow is gone."),
  ('snow', 'wet', "and it's raining. Fantastic."),
  ('snow', 'storm', "and there's a storm coming. Exciting!"),
  ('snow', 'freezing', "and there's ice everywhere."),
  ('snow', 'snow', "and the snow just keeps coming."),
  ('storm', 'clear', "but it's not storming anymore!"),
  ('storm', 'clouds', "and the storm clouds have turned to normal, boring clouds."),
  ('storm', 'wet', "and it's still raining."),
  ('storm', 'storm', "and this storm's not going away yet!"),
  ('storm', 'freezing', "and there's ice everywhere."),
  ('storm', 'snow', "but look! There's snow!"),
  ('freezing', 'clear', "but it's a beautiful, clear day."),
  ('freezing', 'clouds', "but it's cloudy."),
  ('freezing', 'wet', "and here comes some rain"),
  ('freezing', 'storm', "and there's a storm coming. Exciting!"),
  ('freezing', 'freezing', "and there's still ice everywhere."),
  ('freezing', 'snow', "but look! That ice has turned to snow!"),
]
